/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData category = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchased_items = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diposit2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transactions = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_tracking = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fevorite_sellers = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tickets = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tickets2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disputes = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_profile = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData affiliate_product = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buy = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vendor = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData products = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulk_upload = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdraws = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pricing = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physical = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digital = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData license = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
